import {
  Building2,
  UserRound,
  HardHat,
  Wrench,
  Ruler,
  CloudSun,
  CalendarDays,
  CalendarRange,
  CalendarClock,
  Package,
  Truck,
  Forklift,
  Users,
  ClipboardList,
  CircleDollarSign,
  TrendingUp,
  Landmark,
  GanttChartSquare,
  FileDiff,
  MessageCircleQuestion,
  FileCheck2,
  BadgeCheck,
  ListTodo,
  ShieldAlert,
  Stamp,
  AlertTriangle,
  UserCheck,
  Image as ImageIcon,
  Sparkles,
  ListChecks,
  PenLine,
  Paperclip,
  type LucideIcon,
} from "lucide-react";

import type { SectionType } from "@/types";

export const SECTION_ICONS: Record<SectionType, LucideIcon> = {
  project_information: Building2,
  client_information: UserRound,
  builder_information: HardHat,
  contractor_information: Wrench,
  engineer_information: Ruler,
  weather_conditions: CloudSun,
  daily_progress: CalendarDays,
  weekly_progress: CalendarRange,
  look_ahead_schedule: CalendarClock,
  material_usage: Package,
  deliveries: Truck,
  equipment: Forklift,
  labour: Users,
  subcontractor_log: ClipboardList,
  budget: CircleDollarSign,
  cost_forecast: TrendingUp,
  financial_summary: Landmark,
  timeline: GanttChartSquare,
  change_orders: FileDiff,
  rfi_log: MessageCircleQuestion,
  submittals: FileCheck2,
  quality_inspection: BadgeCheck,
  punch_list: ListTodo,
  safety_incidents: ShieldAlert,
  permits_compliance: Stamp,
  risk_register: AlertTriangle,
  visitor_log: UserCheck,
  images: ImageIcon,
  ai_summary: Sparkles,
  recommendations: ListChecks,
  signature: PenLine,
  appendix: Paperclip,
};
