import type { GeneratedReport } from "@/types";
import { formatDate, formatDateTime } from "@/lib/utils";

export interface ReportRenderContext {
  report: GeneratedReport;
  builderName: string;
  builderAddress: string;
  projectAddress: string;
  clientName: string | null;
  contractorName: string | null;
  engineerName: string | null;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function watermarkDataUri(text: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="420" height="220">
    <text x="0" y="120" transform="rotate(-28 210 110)" text-anchor="middle" x="210"
      font-family="Inter, sans-serif" font-size="30" font-weight="700"
      fill="rgba(120,120,120,0.09)">${escapeHtml(text)}</text>
  </svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export function buildReportHtmlDocument(ctx: ReportRenderContext): string {
  const { report, builderName, builderAddress, projectAddress, clientName, contractorName, engineerName } = ctx;
  const { layout } = report;
  const sections = [...report.sections].sort((a, b) => a.order - b.order);

  const pageSizeCss = layout.orientation === "landscape" ? "11in 8.5in" : "8.5in 11in";

  const watermarkStyle = layout.watermark
    ? `background-image: url("${watermarkDataUri(builderName || "DRAFT")}"); background-repeat: repeat;`
    : "";

  const coverPageHtml = layout.coverPage
    ? `<section class="cover-page">
        ${layout.logo ? `<div class="cover-logo">${escapeHtml(builderName)}</div>` : ""}
        <div class="cover-badge">${escapeHtml(report.reportType.replace(/_/g, " ").toUpperCase())}</div>
        <h1 class="cover-title">${escapeHtml(report.name)}</h1>
        <p class="cover-subtitle">${escapeHtml(report.projectName)}</p>
        <div class="cover-meta">
          <div><span>Prepared By</span><strong>${escapeHtml(builderName)}</strong></div>
          ${builderAddress ? `<div><span>Builder Address</span><strong>${escapeHtml(builderAddress)}</strong></div>` : ""}
          ${clientName ? `<div><span>Client</span><strong>${escapeHtml(clientName)}</strong></div>` : ""}
          ${contractorName ? `<div><span>Contractor</span><strong>${escapeHtml(contractorName)}</strong></div>` : ""}
          ${engineerName ? `<div><span>Engineer of Record</span><strong>${escapeHtml(engineerName)}</strong></div>` : ""}
          <div><span>Report Period</span><strong>${formatDate(report.context.dateRangeStart)} – ${formatDate(report.context.dateRangeEnd)}</strong></div>
          <div><span>Generated</span><strong>${formatDateTime(report.createdAt)}</strong></div>
        </div>
      </section>`
    : "";

  const headerHtml = layout.header
    ? `<div class="report-header">
        <span>${escapeHtml(builderName)}</span>
        <span>${escapeHtml(report.name)}</span>
      </div>`
    : "";

  const footerHtml = layout.footer
    ? `<div class="report-footer">
        <span>${escapeHtml(projectAddress)}</span>
        <span>Confidential — Generated by BuildReport AI</span>
      </div>`
    : "";

  const sectionsHtml = sections
    .map(
      (section) => `
      <section class="report-section">
        <h2>${escapeHtml(section.title)}</h2>
        <div class="section-body">${section.html}</div>
      </section>`
    )
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(report.name)}</title>
<style>
  @page { size: ${pageSizeCss}; margin: 0.6in; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: "${layout.font}", "Inter", -apple-system, sans-serif;
    color: ${layout.themeColors.text};
    background: ${layout.themeColors.background};
    ${watermarkStyle}
  }
  .doc-wrapper { max-width: 860px; margin: 0 auto; padding: 32px 40px 64px; }
  .report-header {
    display: flex; justify-content: space-between; align-items: center;
    font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em;
    color: ${layout.themeColors.secondary}; border-bottom: 2px solid ${layout.themeColors.primary};
    padding-bottom: 8px; margin-bottom: 24px;
  }
  .report-footer {
    display: flex; justify-content: space-between; font-size: 10px;
    color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 10px; margin-top: 32px;
  }
  .cover-page {
    min-height: 9in; display: flex; flex-direction: column; justify-content: center;
    padding: 48px 16px; border-bottom: 3px solid ${layout.themeColors.primary}; margin-bottom: 40px;
  }
  .cover-logo { font-weight: 700; font-size: 14px; letter-spacing: 0.06em; color: ${layout.themeColors.primary}; text-transform: uppercase; margin-bottom: 32px; }
  .cover-badge {
    display: inline-block; align-self: flex-start; background: ${layout.themeColors.accent}22;
    color: ${layout.themeColors.accent}; font-size: 11px; font-weight: 700; letter-spacing: 0.08em;
    padding: 4px 10px; border-radius: 999px; margin-bottom: 16px;
  }
  .cover-title { font-size: 34px; font-weight: 800; line-height: 1.15; margin: 0 0 8px; color: ${layout.themeColors.secondary}; }
  .cover-subtitle { font-size: 16px; color: #6b7280; margin: 0 0 32px; }
  .cover-meta { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px 32px; max-width: 640px; }
  .cover-meta div { display: flex; flex-direction: column; gap: 2px; }
  .cover-meta span { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #9ca3af; }
  .cover-meta strong { font-size: 14px; color: ${layout.themeColors.text}; font-weight: 600; }
  .report-section { margin-bottom: 28px; break-inside: avoid; }
  .report-section h2 {
    font-size: 15px; font-weight: 700; color: ${layout.themeColors.primary};
    border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; margin: 0 0 12px;
  }
  .section-body { font-size: 13px; line-height: 1.65; }
  .section-body p { margin: 0 0 10px; }
  .section-body ul { margin: 0 0 10px; padding-left: 20px; }
  .report-table { width: 100%; border-collapse: collapse; font-size: 12px; margin: 8px 0 16px; }
  .report-table th, .report-table td { border: 1px solid #e5e7eb; padding: 6px 10px; text-align: left; vertical-align: top; }
  .report-table th { background: #f9fafb; font-weight: 600; }
</style>
</head>
<body>
  <div class="doc-wrapper">
    ${coverPageHtml}
    ${headerHtml}
    ${sectionsHtml}
    ${footerHtml}
  </div>
</body>
</html>`;
}
